## GENETIC ALGORITHM

One Max Problem

In [ ]:
import random
Population_size = 100
Genome_length = 20
Mutation_rate = 0.01
Crossover_rate = 0.7
Generations = 500

def random_genome(length):
    return [random.randint(0, 1) for i in range(length)]

def initial_population(population_size, genome_length):
    return [random_genome(Genome_length) for i in range(Population_size)]

def fitness(genome):
    return sum(genome)

def selection(population, fitness_values):
    total_fitness = sum(fitness_values)
    pick = random.uniform(0, total_fitness)
    current = 0
    for indiviual, fitness_value in zip(population, fitness_values):
        current += fitness_value
        if current > pick:
            return indiviual

def crossover(parent1,parent2):
    if random.random() < Crossover_rate:
        crossover_location = random.randint(1, len(parent1) -1)
        return parent1[:crossover_location] + parent2[crossover_location:], parent2[:crossover_location] + parent1[crossover_location:]
    else:
        return parent1,parent2
    
def mutation(genome):
    for i in range(len(genome)):
        if random.random() < Mutation_rate:
            genome[i] = abs(genome[i] - 1)
    return genome

def genetic_algorithm():
    population = initial_population(Population_size, Genome_length)
    for generation in range(Generations):
        fitness_values = [fitness(genome) for genome in population]
        new_population = []
        for i in range(Population_size // 2):
            parent1 = selection(population,fitness_values)
            parent2 = selection(population,fitness_values)
            child1,child2 = crossover(parent1,parent2)
            new_population.extend([mutation(child1), mutation(child2)])
            
        population = new_population
        fitness_values = [fitness(genome) for genome in population]
        best_fitness = max(fitness_values)
        print(f"Generation {generation}: Best Fitness = {best_fitness}")

    best_index = fitness_values.index(max(fitness_values))
    best_solution = population[best_index]
    print(f"Best Soltion: {best_solution}")
    print(f"Best Fitness: {fitness(best_solution)}")

genetic_algorithm()

8 Queens Problem

In [60]:
import numpy as np

def initial_population(Population_size, Genome_length):
    population = np.zeros((Population_size, Genome_length), dtype=int)
    for i in range(Population_size):
        population[i] = np.random.permutation(Genome_length)
    return population

def fitness(population,Genome_length):
    fitness_values = []
    for individual in population:
        penalty = 0
        for i in range(Genome_length):
            r = individual[i]
            for j in range(i + 1, Genome_length):
                if individual[j] == r or abs(r - individual[j]) == abs(i - j):
                    penalty += 1
        fitness_values.append(penalty)
    return -np.array(fitness_values)

def rank_selection(population):
    population_fitness = fitness(population)
    ranking = np.argsort(population_fitness)
    ranked_population = population[ranking]
    selected_population = ranked_population[:Population_size //2]
    selected_population = np.tile(swap_mutation(selected_population, 1.0), (2, 1))
    np.random.shuffle(selected_population[Population_size //2:])
    return selected_population

def roulette_selection(population, Genome_length):
    chances = fitness(population, Genome_length)
    chances += abs(chances.min()) +1
    chances = chances/chances.sum()
    n = len(population)
    indicies = np.arange(n)
    selected_indicies = np.random.choice(indicies, size = n, p = chances, replace = True)
    selected_population = population[selected_indicies]
    return selected_population

def crossover(parent1, parent2,Crossover_rate, Genome_length):
    point = np.random.randint(1, Genome_length)
    if np.random.random() < Crossover_rate:
        child1 = np.concatenate([parent1[:point], parent2[point:]])
        child2 = np.concatenate([parent2[:point], parent1[point:]])
    else:
        child1 = parent1.copy()
        child2 = parent2.copy()
    return child1, child2

def swap_mutation(population,Mutation_rate, Genome_length):
    for individual in population:
        if np.random.random() < Mutation_rate:
            position1 = np.random.randint(0, Genome_length)
            position2 = np.random.randint(0, Genome_length)
            individual[position1], individual[position2] = individual[position2], individual[position1]
    return population

def random_mutation(population,Mutation_rate, Genome_length):
    for individual in population:
        if np.random.random() < Mutation_rate:
            i = np.random.randint(Genome_length)
            individual[i] = np.random.randint(Genome_length)
    return population

def Crossover_Mutation(population, Crossover_rate, Mutation_rate, Genome_length):
    crossed_population = []
    Population_size = len(population)
    for i in range(0, Population_size, 2):
        parent1 = population[i]
        parent2 = population[i + 1]
        child1, child2 = crossover(parent1, parent2,Crossover_rate, Genome_length)
        crossed_population.append(child1)
        crossed_population.append(child2)

    mutated_population = random_mutation(crossed_population, Mutation_rate, Genome_length)
    return np.array(mutated_population)

def Eight_Queens(Population_size,Genome_length,Mutation_rate,Crossover_rate,Generations):
    Global_Best_Fitness = None
    population = initial_population(Population_size,Genome_length) #Initial population

    for generation in range(Generations):
        Population_fitness = fitness(population, Genome_length) #Fitness calculation
        best_fitness = Population_fitness[Population_fitness.argmax()]

        if Global_Best_Fitness is None or best_fitness > Global_Best_Fitness:
            Global_Best_Fitness = best_fitness
            best_solution = population[Population_fitness.argmax()]
        print(f"\rGeneration = {generation:06}  -f= {-Global_Best_Fitness:03}", end = " ")
        if best_fitness == 0:
            print("\nOptimal Solution Found")
            print(population[Population_fitness.argmax()])
            break
        selected_population = roulette_selection(population, Genome_length) #Selection
        population = Crossover_Mutation(selected_population, Crossover_rate, Mutation_rate, Genome_length) #Cross over and mutation

Eight_Queens(300, 8, 0.1, 0.7, 10000)


Generation = 000839  -f= 000 
Optimal Solution Found
[3 5 7 1 6 0 2 4]


### Binary Pattern Optimization

In [10]:
import numpy as np

def initialize(population_size,genome_size):
    population = np.zeros((population_size, genome_size), dtype=int)
    for individual in population:
        for i in range(len(individual)):
            individual[i] = random.randint(0,1)
    return population

def fitness(population):
    fitness_values = []
    for individual in population:
        index = len(fitness_values)
        fitness_values.append(0)
        for i in range(1, len(individual) - 1):
            if individual[i] == 1 and individual[i -1] == 0 and individual[i +1] == 0:
                fitness_values[index] += 1
    return fitness_values

def selection(population, fitness_values):
    new_population = []
    fitness_index = np.argsort(fitness_values)[::-1]
    for i in range(len(population) // 2):
        new_population.append(population[fitness_index[i]])
    return np.array(new_population)

def crossover(parent1, parent2, genome_size):
    new_population = []
    singularity = np.random.randint(0,genome_size)
    child1 = np.concatenate([parent1[:singularity], parent2[singularity:]])
    child2 = np.concatenate([parent2[:singularity], parent1[singularity:]])
    new_population = np.vstack([parent1, parent2, child1, child2])
    return np.array(new_population)

def mutation(population, population_size, genome_size):
    index1 = np.random.randint(0, population_size)
    index2 = np.random.randint(0, genome_size)
    if population[index1,index2] == 0:
        population[index1,index2] = 1
    else:
        population[index1,index2] = 0
    return population

def Main(population_size, genome_size, generations):
    population = initialize(population_size, genome_size)
    print(f"============================\nInitial Population: \n{population}\nInitial Fitness: {fitness(population)}\n============================")
    for k in range(generations):
        selected = selection(population,fitness(population))
        crossed = []
        for i in range( 0, len(selected), 2):
            if i + 1 < len(selected):
                children = crossover(selected[i], selected[i+1], genome_size)
                crossed.extend(children)
        crossed = np.array(crossed)
        if len(crossed) < population_size:
            while len(crossed) < population_size:
                random_individual = selected[np.random.randint(len(selected))]
                crossed = np.vstack([crossed, random_individual])
        mutated = mutation(crossed, population_size, genome_size)
        population = mutated
        print(f"Iteration {k+1}: \n{population}\nCurrent Fitness: {fitness(population)} \n============================")

Main(4, 9, 2)

Initial Population: 
[[1 1 1 0 1 0 1 1 1]
 [1 1 1 1 0 0 1 1 0]
 [0 1 0 0 0 0 1 1 1]
 [0 1 1 0 0 1 1 1 1]]
Initial Fitness: [1, 0, 1, 0]
Iteration 1: 
[[0 1 0 0 0 0 1 1 1]
 [1 1 1 0 1 0 1 1 1]
 [0 1 0 0 0 0 1 1 1]
 [1 1 0 0 1 0 1 1 1]]
Current Fitness: [1, 1, 1, 1] 
Iteration 2: 
[[1 1 0 0 1 0 1 1 1]
 [0 1 0 1 0 0 1 1 1]
 [1 1 0 0 0 0 1 1 1]
 [0 1 0 0 1 0 1 1 1]]
Current Fitness: [1, 2, 0, 2] 
